ipfixcol: check for libxml2-devel in configure
Configuration format of ipfixcol is XML so we will need to use libxml2
library. This commit adds checking for and linking libxml2 by configure
script.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -608,6 +608,7 @@ LIBOBJS
 EGREP
 GREP
 CPP
+XML2_CONFIG
 SET_MAKE
 INSTALL_DATA
 INSTALL_SCRIPT
@@ -674,6 +675,7 @@ ac_subst_files=''
 ac_user_opts='
 enable_option_checking
 with_distro
+with_libxml2_path
 '
       ac_precious_vars='build_alias
 host_alias
@@ -1295,6 +1297,7 @@ Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-distro=DISTRO    Compile for specific Linux distribution
+  --with-libxml2-path=DIR Path prefix to Libxml2 library
 
 Some influential environment variables:
   CC          C compiler command
@@ -1423,6 +1426,52 @@ fi
   as_fn_set_status $ac_retval
 
 } # ac_fn_c_try_compile
+
+# ac_fn_c_try_link LINENO
+# -----------------------
+# Try to link conftest.$ac_ext, and return whether this succeeded.
+ac_fn_c_try_link ()
+{
+  as_lineno=${as_lineno-"$1"} as_lineno_stack=as_lineno_stack=$as_lineno_stack
+  rm -f conftest.$ac_objext conftest$ac_exeext
+  if { { ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval ac_try_echo="\"\$as_me:${as_lineno-$LINENO}: $ac_try_echo\""
+$as_echo "$ac_try_echo"; } >&5
+  (eval "$ac_link") 2>conftest.err
+  ac_status=$?
+  if test -s conftest.err; then
+    grep -v '^ *+' conftest.err >conftest.er1
+    cat conftest.er1 >&5
+    mv -f conftest.er1 conftest.err
+  fi
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext && {
+	 test "$cross_compiling" = yes ||
+	 $as_test_x conftest$ac_exeext
+       }; then :
+  ac_retval=0
+else
+  $as_echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_retval=1
+fi
+  # Delete the IPA/IPO (Inter Procedural Analysis/Optimization) information
+  # created by the PGI compiler (conftest_ipa8_conftest.oo), as it would
+  # interfere with the next link command; also delete a directory that is
+  # left behind by Apple's compiler.  We do this before executing the actions.
+  rm -rf conftest.dSYM conftest_ipa8_conftest.oo
+  eval $as_lineno_stack; ${as_lineno_stack:+:} unset as_lineno
+  as_fn_set_status $ac_retval
+
+} # ac_fn_c_try_link
 
 # ac_fn_c_try_cpp LINENO
 # ----------------------
@@ -1801,52 +1850,6 @@ $as_echo "$ac_res" >&6; }
   eval $as_lineno_stack; ${as_lineno_stack:+:} unset as_lineno
 
 } # ac_fn_c_find_uintX_t
-
-# ac_fn_c_try_link LINENO
-# -----------------------
-# Try to link conftest.$ac_ext, and return whether this succeeded.
-ac_fn_c_try_link ()
-{
-  as_lineno=${as_lineno-"$1"} as_lineno_stack=as_lineno_stack=$as_lineno_stack
-  rm -f conftest.$ac_objext conftest$ac_exeext
-  if { { ac_try="$ac_link"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval ac_try_echo="\"\$as_me:${as_lineno-$LINENO}: $ac_try_echo\""
-$as_echo "$ac_try_echo"; } >&5
-  (eval "$ac_link") 2>conftest.err
-  ac_status=$?
-  if test -s conftest.err; then
-    grep -v '^ *+' conftest.err >conftest.er1
-    cat conftest.er1 >&5
-    mv -f conftest.er1 conftest.err
-  fi
-  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
-  test $ac_status = 0; } && {
-	 test -z "$ac_c_werror_flag" ||
-	 test ! -s conftest.err
-       } && test -s conftest$ac_exeext && {
-	 test "$cross_compiling" = yes ||
-	 $as_test_x conftest$ac_exeext
-       }; then :
-  ac_retval=0
-else
-  $as_echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-	ac_retval=1
-fi
-  # Delete the IPA/IPO (Inter Procedural Analysis/Optimization) information
-  # created by the PGI compiler (conftest_ipa8_conftest.oo), as it would
-  # interfere with the next link command; also delete a directory that is
-  # left behind by Apple's compiler.  We do this before executing the actions.
-  rm -rf conftest.dSYM conftest_ipa8_conftest.oo
-  eval $as_lineno_stack; ${as_lineno_stack:+:} unset as_lineno
-  as_fn_set_status $ac_retval
-
-} # ac_fn_c_try_link
 
 # ac_fn_c_check_func LINENO FUNC VAR
 # ----------------------------------
@@ -2342,6 +2345,14 @@ if test "${with_distro+set}" = set; then :
 else
   DISTRO=redhat
 
+fi
+
+
+# Add --with-libxml2-path parameter
+
+# Check whether --with-libxml2-path was given.
+if test "${with_libxml2_path+set}" = set; then :
+  withval=$with_libxml2_path;
 fi
 
 
@@ -3531,10 +3542,99 @@ fi
 
 ############################ Check for libraries ###############################
 
+### LibXML2 ###
+# Test whether Libxml2 exist
+if test -n "$with_libxml2_path" ; then
+	LIBS_LIB_XML="-lxml2"
+	LDFLAGS_LIB_XML="-L$with_libxml2_path/lib"
+else
+
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for main in -lxml2" >&5
+$as_echo_n "checking for main in -lxml2... " >&6; }
+if ${ac_cv_lib_xml2_main+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lxml2  $LIBS"
+cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+return main ();
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_link "$LINENO"; then :
+  ac_cv_lib_xml2_main=yes
+else
+  ac_cv_lib_xml2_main=no
+fi
+rm -f core conftest.err conftest.$ac_objext \
+    conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_xml2_main" >&5
+$as_echo "$ac_cv_lib_xml2_main" >&6; }
+if test "x$ac_cv_lib_xml2_main" = xyes; then :
+   LIBS_LIB_XML="-lxml2"
+else
+   echo "Libxml2 not found - exiting! (use --with-libxml2-path=DIR if you has it in some other directory)" ; exit 1
+fi
+
+fi
+# Extract the first word of "xml2-config", so it can be a program name with args.
+set dummy xml2-config; ac_word=$2
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
+$as_echo_n "checking for $ac_word... " >&6; }
+if ${ac_cv_prog_XML2_CONFIG+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  if test -n "$XML2_CONFIG"; then
+  ac_cv_prog_XML2_CONFIG="$XML2_CONFIG" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+    for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_prog_XML2_CONFIG=""yes""
+    $as_echo "$as_me:${as_lineno-$LINENO}: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+  done
+IFS=$as_save_IFS
+
+  test -z "$ac_cv_prog_XML2_CONFIG" && ac_cv_prog_XML2_CONFIG=""no""
+fi
+fi
+XML2_CONFIG=$ac_cv_prog_XML2_CONFIG
+if test -n "$XML2_CONFIG"; then
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: $XML2_CONFIG" >&5
+$as_echo "$XML2_CONFIG" >&6; }
+else
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+fi
+
+
+if test "$XML2_CONFIG" = "no"; then
+	echo "xml2-config not found - exiting!"
+	exit 1
+fi
+CFLAGS="$CFLAGS `xml2-config --cflags`"
+LIBS="$LIBS $LIBS_LIB_XML"
+LDFLAGS="$LDFLAGS $LDFLAGS_LIB_XML"
+
 ###################### Check for configure parameters ##########################
 
 ######################### Checks for header files ##############################
-
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -70,6 +70,10 @@ AC_ARG_WITH([distro],
 	DISTRO=redhat
 )
 
+# Add --with-libxml2-path parameter
+AC_ARG_WITH([libxml2-path],
+	AC_HELP_STRING([--with-libxml2-path=DIR],[Path prefix to Libxml2 library]))
+
 ############################ Check for programs ################################
 
 # in case of cross-compilation, try to gues cross-compiler if not set
@@ -165,6 +169,25 @@ AC_PROG_INSTALL
 AC_PROG_MAKE_SET
 
 ############################ Check for libraries ###############################
+
+### LibXML2 ###
+# Test whether Libxml2 exist
+if test -n "$with_libxml2_path" ; then
+	LIBS_LIB_XML="-lxml2"
+	LDFLAGS_LIB_XML="-L$with_libxml2_path/lib"
+else
+	AC_CHECK_LIB([xml2], [main],
+		[ LIBS_LIB_XML="-lxml2"],
+		[ echo "Libxml2 not found - exiting! (use --with-libxml2-path=DIR if you has it in some other directory)" ; exit 1 ])
+fi
+AC_CHECK_PROG([XML2_CONFIG], [xml2-config], ["yes"], ["no"])
+if test "$XML2_CONFIG" = "no"; then
+	echo "xml2-config not found - exiting!"
+	exit 1
+fi
+CFLAGS="$CFLAGS `xml2-config --cflags`"
+LIBS="$LIBS $LIBS_LIB_XML"
+LDFLAGS="$LDFLAGS $LDFLAGS_LIB_XML"
 
 ###################### Check for configure parameters ##########################
 
