ipfixcol: plugins man pages

diff --git a/base/src/intermediate/filter/Makefile.am b/base/src/intermediate/filter/Makefile.am
--- a/base/src/intermediate/filter/Makefile.am
+++ b/base/src/intermediate/filter/Makefile.am
@@ -16,3 +16,22 @@ parser.h parser.c: parser.y
 
 scanner.h scanner.c: scanner.l
 	$(FLEX) -o scanner.c --header-file=scanner.h $<
+
+MANSRC = ipfixcol-filter-inter.dbk
+EXTRA_DIST = $(MANSRC)
+man_MANS = ipfixcol-filter-inter.1
+CLEANFILES += ipfixcol-filter-inter.1
+
+%.1 : %.dbk
+	@if [ -n "$(XSLTPROC)" ]; then \
+		if [ -f "$(XSLTMANSTYLE)" ]; then \
+			echo $(XSLTPROC) $(XSLTMANSTYLE) $<; \
+			$(XSLTPROC) $(XSLTMANSTYLE) $<; \
+		else \
+			echo "Missing $(XSLTMANSTYLE)!"; \
+			exit 1; \
+		fi \
+	else \
+		echo "Missing xsltproc"; \
+	fi
+
diff --git a/base/src/storage/forwarding/Makefile.am b/base/src/storage/forwarding/Makefile.am
--- a/base/src/storage/forwarding/Makefile.am
+++ b/base/src/storage/forwarding/Makefile.am
@@ -6,3 +6,22 @@ ipfixcol_forwarding_output_la_LDFLAGS = -module -avoid-version -shared
 ipfixcol_forwarding_output_la_LIBADD = -lsctp -lrt
 
 ipfixcol_forwarding_output_la_SOURCES = forwarding.c
+
+MANSRC = ipfixcol-forwarding-output.dbk
+EXTRA_DIST = $(MANSRC)
+man_MANS = ipfixcol-forwarding-output.1
+CLEANFILES = ipfixcol-forwarding-output.1
+
+%.1 : %.dbk
+	@if [ -n "$(XSLTPROC)" ]; then \
+		if [ -f "$(XSLTMANSTYLE)" ]; then \
+			echo $(XSLTPROC) $(XSLTMANSTYLE) $<; \
+			$(XSLTPROC) $(XSLTMANSTYLE) $<; \
+		else \
+			echo "Missing $(XSLTMANSTYLE)!"; \
+			exit 1; \
+		fi \
+	else \
+		echo "Missing xsltproc"; \
+	fi
+
