IPFIXcol: Incorporated new ipfixviewer, bugfixes in the building system
Increased version number to 0.5 and pushed to stable repository

diff --git a/base/src/input/ipfix/Makefile.am b/base/src/input/ipfix/Makefile.am
--- a/base/src/input/ipfix/Makefile.am
+++ b/base/src/input/ipfix/Makefile.am
@@ -5,3 +5,23 @@ plugins_LTLIBRARIES = ipfixcol-ipfix-input.la
 ipfixcol_ipfix_input_la_LDFLAGS = -module -avoid-version -shared
 
 ipfixcol_ipfix_input_la_SOURCES = ipfix_file.c
+
+
+MANSRC = ipfixcol-ipfix-input.dbk
+EXTRA_DIST = $(MANSRC)
+man_MANS = ipfixcol-ipfix-input.1
+CLEANFILES = ipfixcol-ipfix-input.1
+
+%.1 : %.dbk
+	@if [ -n "$(XSLTPROC)" ]; then \
+		if [ -f "$(XSLTMANSTYLE)" ]; then \
+			echo $(XSLTPROC) $(XSLTMANSTYLE) $<; \
+			$(XSLTPROC) $(XSLTMANSTYLE) $<; \
+		else \
+			echo "Missing $(XSLTMANSTYLE)!"; \
+			exit 1; \
+		fi \
+	else \
+		echo "Missing xsltproc"; \
+	fi
+
