ipfixdump: Updated files formatting. Added configuration and make parameters for doxygen

diff --git a/devel-tools/ipfixdump/Makefile b/devel-tools/ipfixdump/Makefile
--- a/devel-tools/ipfixdump/Makefile
+++ b/devel-tools/ipfixdump/Makefile
@@ -18,6 +18,10 @@ OBJDIR  = .obj
 SRCDIR  = src
 SRC3RD  = 3rdparty
 
+DOXYGEN = doxygen
+DOXYGEN_CONFIG = doxyconf
+DOXYGEN_DIR = doc
+
 # scanner must be build before filter (filter includes scanner's header)
 OBJS    = $(OBJDIR)/scanner.o $(SRCS:%.cpp=$(OBJDIR)/%.o) $(OBJDIR)/pugi.o
 
@@ -45,6 +49,22 @@ $(OBJDIR)/scanner.o: $(SRCDIR)/scanner.c
 $(SRCDIR)/scanner.c: $(SRCDIR)/scanner.l
 	flex -o $(SRCDIR)/scanner.c --header-file=$(SRCDIR)/scanner.h $<
 
+.PHONY: doc
+doc: doxygen
+
+doxygen: $(DOXYGEN_CONFIG) $(SRCS:%=$(SRCDIR)/%)
+	@[ -d $(DOXYGEN_DIR) ] || mkdir -p $(DOXYGEN_DIR); \
+	if [ -n "$(DOXYGEN)" ]; then \
+		(cat $(DOXYGEN_CONFIG); \
+		echo 'OUTPUT_DIRECTORY = $(DOXYGEN_DIR)' ) | \
+		$(DOXYGEN) - > /dev/null; \
+	else \
+		echo "Missing doxygen"; \
+		exit 1; \
+	fi
+
+
 clean:
 	rm -f ipfixdump $(OBJDIR)/*
 	rm -f src/protocols.cpp src/scanner.h src/scanner.c
+	rm -fr doc 
