Fastbit: MAINTENANCE - added fastbit manpage to Makefile

diff --git a/src/storage/fastbit/Makefile.in b/src/storage/fastbit/Makefile.in
--- a/src/storage/fastbit/Makefile.in
+++ b/src/storage/fastbit/Makefile.in
@@ -3,7 +3,12 @@ CFLAGS  = @CFLAGS@
 LIBS    = @LIBS@
 INCLUDE = "-I../../../"
 
+XSLTPROC = @XSLTPROC@
+XSLTMANSTYLE = @XSLTMANSTYLE@
+
 all: fastbit_output.so nffile2fastbit
+
+doc: fastbit.1
 
 fastbit_output.so: fastbit_output.o fastbit_element.o fastbit_table.o pugixml.o
 	g++ $(CFLAGS) $(LIBS) -lfastbit -L/usr/local/lib -shared -Wl,-soname,fastbit_output.so.1 fastbit_output.o fastbit_element.o fastbit_table.o pugixml.o -o $@ -lc
@@ -22,6 +27,20 @@ pugixml.o: pugixml/pugixml.cpp
 
 nffile2fastbit: nffile2fastbit.c
 	$(CC) $(CFLAGS) $(LIBS) -o $@ $<
+
+%.1 %.2 %.3 %.4 %.5 %.6 %.7 %.8 %.9: %.dbk
+	@if [ -n "$(XSLTPROC)" ]; then \
+		if [ -f "$(XSLTMANSTYLE)" ]; then \
+			echo $(XSLTPROC) $(XSLTMANSTYLE) $<; \
+			$(XSLTPROC) $(XSLTMANSTYLE) $<; \
+		else \
+			echo "Missing $(XSLTMANSTYLE)!"; \
+			exit 1; \
+		fi \
+	else \
+		echo "Missing xsltproc"; \
+	fi
+
 
 clean:
 	-rm fastbit_output.so *.o nffile2fastbit
